---
- name: Extract a file on web1 /root on web1 to /srv on web1 
  hosts: web1
  tasks:
  - unarchive:
      src: /root/data.tar.gz
      dest: /srv/
      remote_src: yes
  - file:
      path: /root/data.tar.gz
      state: absent