- name: Add block to index.html
  hosts: web1
  tasks:
   - blockinfile:
      create: yes
      owner: apache
      group: apache
      insertbefore: BOF
      path: /var/www/html/index.html
      block: |
       Welcome my friend!
       This is Ansible Lab.